feat: Add modal component
knoxville-utilities-board/nrg-ui pull request #135
Opened 2024-09-06 13:19 UTC by KeithClinard

2024-09-10 19:06 UTC, TSenter requested changes

2024-10-03 15:00 UTC, TSenter requested changes
Are modals not dismissible by clicking on the background? Here's [a CodePen](https://codepen.io/aslhnates/pen/KKKpmpd) that gives an sample implementation.

2024-10-03 16:07 UTC, KeithClinard commented on apps/test-app/tests/integration/components/modal-test.gts
Does this test cover that use-case?
https://github.com/knoxville-utilities-board/nrg-ui/blob/fc28554ff5c456213f6d1ad19a7bc31e74e9d3a1/apps/test-app/tests/integration/components/modal-test.gts#L41-L50

2024-10-03 17:12 UTC, TSenter approved these changes

2024-10-03 17:13 UTC, merged