chore: Use Embroider for docs app
knoxville-utilities-board/nrg-ui pull request #138
Opened 2024-09-13 12:44 UTC by TSenter

2024-09-13 19:27 UTC, KeithClinard requested changes

2024-09-13 19:27 UTC, KeithClinard commented on package.json
> +    "start:test-app": "pnpm --filter test-app start",
```suggestion
    "start:test-app": "pnpm --filter test-app start",
    "start:docs-app": "pnpm --filter docs-app start",
```

2024-09-13 19:27 UTC, KeithClinard commented on package.json
> +    "start:test-app": "pnpm --filter test-app start",
I also had to add `-p 4201` to the test app's `ember serve` script

2024-09-15 21:08 UTC, fdlane approved these changes

2024-09-16 12:39 UTC, KeithClinard approved these changes

2024-09-16 12:39 UTC, merged