fix: Change icon spacing based on type
knoxville-utilities-board/nrg-ui pull request #174
Opened 2024-10-04 14:38 UTC by bnhkubpublic

The previous change corrected icon spacing for image based icons but alpha-numeric icons are now misaligned. This should add a property that, when true, any alpha-numeric character inside the icon property within `d-flex` flex boxes will be aligned evenly.

2024-10-04 14:44 UTC, TSenter requested changes

2024-10-04 14:44 UTC, TSenter commented on packages/ember-core/src/components/mktg/feature-list.gts
This feels like a workaround for the underlying problem. If the surrounding `p` tag is using flex, why not use the [flex utilities](https://getbootstrap.com/docs/5.3/utilities/flex/#align-items)? We don't know that this hardcoded margin will work on larger sizes.

2024-10-04 15:48 UTC, bnhkubpublic commented on packages/ember-core/src/components/mktg/feature-list.gts
I've tested a few implementations and I think I'll revert my margin tag and use the flex utility `align-items-baseline` to work with all size of flex box.

2024-10-04 18:04 UTC, TSenter commented on packages/ember-core/src/components/mktg/feature-list.gts
Does this still need the `me-2` class?

2024-10-07 14:55 UTC, TSenter approved these changes

2024-10-07 14:55 UTC, merged