feat: Implement service pricing component
knoxville-utilities-board/nrg-ui pull request #37
Opened 2024-07-29 19:19 UTC by Trishu-Patel

![Screenshot 2024-07-29 151654](https://github.com/user-attachments/assets/0b9d356c-e8d2-43b5-b11c-4a9226ee6f53)
![Screenshot 2024-07-29 151636](https://github.com/user-attachments/assets/43dfde1c-d92b-4bd5-a548-dc1be6e63d7a)

2024-08-01 18:01 UTC, lnicely requested changes

2024-08-01 18:02 UTC, ChesneyJulian commented on packages/ember/src/components/mktg/service-pricing.gts
> +    {{yield (component Addon)}}
Should we make this a yield hash so the implementation is more aligned with other components of this nature?

2024-08-01 18:03 UTC, ChesneyJulian commented on packages/ember/src/components/mktg/service-pricing.gts
> +    {{yield (component Addon)}}
Implementation in the test app would look more like this:
`<Mktg::ServicePricing as |Service|>
    <Service.Addon />
</Mktg::ServicePricing>`

2024-08-01 18:04 UTC, lnicely commented on packages/ember/src/components/mktg/service-pricing.gts
> +    addon?: string;
Can we rename this to `label`?

2024-08-01 18:28 UTC, ChesneyJulian commented on packages/ember-test-app/app/templates/marketing.hbs
> +      @descriptionDisabled = {{true}}
I think we collectively decided to use the @active param for determining the "Select", if not active and no selection made, then gray and underlined, if not active and selection is made, bolded price

2024-08-01 18:29 UTC, lnicely commented on packages/ember-test-app/app/templates/marketing.hbs
> +      @serviceType="The Gig"
```suggestion
      @name="Fiber"
      @type="The Gig"
```

2024-08-02 18:26 UTC, lnicely commented on packages/ember-test-app/app/templates/marketing.hbs
> +      @type="The Gig"
I don't see the type property listed in the component. Should this be `package`?

2024-08-06 14:13 UTC, lnicely approved these changes

2024-08-06 14:18 UTC, merged