feat: Implement noBorder param for cards
knoxville-utilities-board/nrg-ui pull request #47
Opened 2024-08-02 13:06 UTC by ChesneyJulian

This PR allows the cards to be passed a param of noBorder 
![image](https://github.com/user-attachments/assets/5dd1ad3c-94f5-496b-ae45-bfebf51244c9)

2024-08-02 13:37 UTC, lnicely commented on packages/ember/src/components/card.gts
> +      class="card p-4 shadow-sm {{if @noBorder 'border-0'}}"
Should we rename this to `hasBorder`? Default it to yes, but if `hasBorder={{false}}` then we add `border-0`?

2024-08-02 17:59 UTC, lnicely approved these changes

2024-08-05 16:22 UTC, TSenter requested changes

2024-08-05 17:50 UTC, TSenter approved these changes

2024-08-05 17:50 UTC, merged